# Generated by Django 3.2.8 on 2021-10-20 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('RU', 'Running'), ('ER', 'Error'), ('CO', 'Complete'), ('NF', 'Not-Found')], default='AC', max_length=15)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
